// glossaryファイル Command_prompt
`use strict`
const glossary = [
{target:`mkdir`, content:`ディレクトリを作成する。<br>$ *** command_prompt_test`},
{target:`cd`, content:`カレントディレクトリを変更。<br>$ *** ./command_prompt_test`},
{target:`echo`, content:`任意の文字列を画面に表示。<br>$ *** 'Hello world'<br>$ *** '{ 'private': true }' >> package.json<br> → package.jsonファイル書込み（ファイルが無い場合は自動作成）`},
{target:`>>`, content:`echo コマンドの出力を package.json ファイルの末尾に追加。<br>$ echo '{ 'private': true }' *** package.json`},
{target:`type`, content:`ファイルの内容を表示する。<br>$ *** package.json → { 'private': true }`},
{target:`rd`, content:`ディレクトリを削除する。<br>$ *** deleteDir`},
{target:`dir`, content:`ディレクトリの内容を表示する。<br>$ ***`},
{target:`curl`, content:`コマンドラインからデータをURLを介して転送するためのツール。ウェブサーバーへのリクエストやAPIのテストなどに広く使用。<br>$ *** https://www.yahoo.co.jp/ → 指定したURLコンテンツを取得`},
{target:`help`, content:`コマンドのヘルプを表示。<br>$ *** copy`},
{target:`/?`, content:`コマンドのヘルプを表示。<br>$ copy ***`},
{target:`date`, content:`日付を設定・表示。<br>$ ***<br>$ *** /T`},
{target:`time`, content:`時刻を設定・表示。<br>$ ***<br>$ *** /T`},
{target:`calc`, content:`計算機の起動。<br>$ ***`},
{target:`attrib`, content:`ファイル属性の表示と設定。<br>$ *** package.json`},
{target:`tree`, content:`フォルダ構造を図式表示。<br>$ ***`},
{target:`copy`, content:`ファイルをコピー。<br>$ *** example.txt ./new_dir`},
{target:`del`, content:`ファイルを削除。<br>$ *** example.txt`},
{target:`find`, content:`ファイルの中からテキストを検索。<br>$ *** 'test' example.txt`},
{target:`findstr`, content:`文字列や正規表現を使って検索。<br>$ *** 'te*' example.txt`},
{target:`more`, content:`ファイルの内容をページごとに表示。<br>$ *** example.txt`},
{target:`move`, content:`ファイルの移動・名称変更。<br>$ *** example.txt ./new_dir`},
{target:`ren / rename`, content:`ファイル名・ディレクトリ名を変更。<br>$ ren oldname.txt newname.txt`},
{target:`replace`, content:`ファイルを置き換える。<br>$ *** example.txt ./new_dir`},
{target:`xcopy`, content:`ファイルをディレクトリ構造ごとコピー。<br>$ *** ./new_dir ./new2_dir`},
{target:`robocopy`, content:`ファイルやフォルダをコピー。<br>$ *** ./new_dir ./new3_dir`},
{target:`sort`, content:`データを並べ替える。<br>$ *** example.txt`},
{target:`where`, content:`ファイルを検索。<br>$ *** example.xlsx`},
{target:`comp`, content:`2つのファイルをバイナリ比較。<br>$ *** example.txt example2.txt`},
{target:`fc`, content:`2つのファイルを比較して違いを表示。<br>$ *** example.txt example2.txt`},
{target:`hostname`, content:`ホスト名を表示。<br>$ ***`},
{target:`systeminfo`, content:`システム構成情報を表示。<br>$ ***`},
{target:`ver`, content:`Windowsのバージョンを表示。<br>$ ***`},
{target:`whoami`, content:`ログイン中ユーザの情報を表示。<br>$ ***`},
{target:`getmac`, content:`MACアドレスを表示。<br>$ ***`},
{target:`nbtstat`, content:`NetBIOSの状態を表示。<br>$ *** -c`},
{target:`vol`, content:`ディスクのボリュームラベルを表示。<br>$ *** C:`},
{target:`assoc`, content:`拡張子の関連付けの表示・設定。<br>$ *** .txt`},
{target:`set`, content:`環境変数を表示・設定。<br>$ *** PATH`},
{target:`ipconfig`, content:`ネットワーク設定を確認。<br>$ ***`},
{target:`path`, content:`ファイル・プログラムのディレクトリを表示/設定。<br>$ *** C:/Windows/System32`},
{target:`tasklist`, content:`実行中プロセスの一覧表示。<br>$ ***`},
{target:`taskkill`, content:`指定したタスクの終了。<br>$ *** /F /IM EXCEL.EXE`},
{target:`chcp`, content:`コンソールの文字コード表示/設定。<br>$ ***`},
{target:`title`, content:`コマンドプロンプトウィンドウのタイトルを設定。<br>$ *** MyTitle`},
{target:`clip`, content:`コマンドの出力をクリップボードにコピー。<br>$ *** < example.txt`},
{target:`cls`, content:`コマンドプロンプト画面をクリア。<br>$ ***`},
{target:`cmd`, content:`新しいコマンドプロンプトを起動。<br>$ ***`},
{target:`exit`, content:`コマンドプロンプトを終了。<br>$ ***`},
{target:`prompt`, content:`コマンドプロンプトを変更。<br>$ *** $P$G`},
{target:`start`, content:`新規コマンドプロンプトを開く。<br>$ *** cmd`},
{target:`shutdown`, content:`シャットダウン/再起動/ログオフ。<br>$ shutdown /s`},
{target:`ftp`, content:`ファイルを転送。<br>$ *** example.com`},
{target:`net`, content:`ネットワーク操作。<br>$ *** user`},
{target:`netstat`, content:`ネットワーク統計を表示。<br>$ *** -an`},
{target:`choice`, content:`ユーザー入力を受付ける。<br>$ *** /M 'Yes or No?'`},
{target:`endlocal`, content:`バッチファイルの環境変数のローカル化を終了。<br>$ ***`},
{target:`for`, content:`ループ処理を実行。<br>$ *** %i in (*) do @echo %i → 現在のディレクトリ内のすべてのファイルとフォルダの名前が一行ずつ表示<br>%i：ループ変数<br>(*)：すべてのファイルやフォルダを表す。*はワイルドカード<br>do：ループ内で実行するコマンドの指定<br>@echo %i：表示（@はコマンド自体を表示しないために使用）`},
{target:`if`, content:`条件処理を行う。<br>$ *** exist example.txt echo found`},
{target:`pause`, content:`処理を一時停止。<br>$ ***`},
{target:`rem`, content:`バッチ ファイルまたは CONFIG.SYSにコメントを記述。<br>$ *** This is a comment`},
{target:`print`, content:`テキストファイルを印刷。<br>$ *** /D:LPT1 example.txt`},
{target:`defrag`, content:`ディスクを最適化。<br>$ *** C: /U /V`},
{target:`cacls`, content:`アクセス権を設定・表示。<br>$ *** example.txt → 表示<br>$ *** example.txt /G UserNameA:F → UserNameAにフルコントロールのアクセス権を設定`},
{target:`color`, content:`コンソールの色を設定。<br>$ *** 0F → 背景：0 黒、文字：F 輝く白`},
{target:`nslookup`, content:`DNSサーバを問い合わせる。<br>$ *** example.com`},
{target:`pathping`, content:`経路の追跡と統計を表示。<br>$ *** example.com`},
{target:`ping`, content:`ネットワークの疎通を確認。<br>$ *** example.com`},
{target:`pathpping/ tracert`, content:`ネットワークの経路を追跡。<br>$ *** example.com`},
{target:`tracert`, content:`ネットワークの経路を確認。<br>$ *** www.example.com`},
{target:`call`, content:`バッチファイルを呼び出す。<br>$ *** script.bat`},
{target:`cscript`, content:`スクリプトファイルを実行。<br>$ *** script.vbs`},
{target:`logoff`, content:`セッションを終了。<br>$ ***`},
{target:`route`, content:`ルーティングテーブルを表示/編集。<br>$ ***`},
{target:`arp`, content:`ARPキャッシュを表示/編集。<br>$ *** -a`},
{target:`ftype`, content:`拡張子に関連したアプリケーションを設定。<br>$ *** txtfile → 一覧表示<br>$ *** txtfile → txtfileのアプリケーション表示<br>$ *** txtfile=C:/Program.exe %1 → txtfileのアプリケーションを設定`},
{target:`format`, content:`ディスクをフォーマット。<br>$ *** C:`},
{target:`recover`, content:`欠陥ディスクからファイルを回復。<br>$ *** lostfile.txt`},
{target:`chkdsk`, content:`ディスクの状態をチェック。<br>$ *** C:`},
{target:`chkntfs`, content:`起動時のディスクチェックを設定。<br>$ *** /D`},
{target:`label`, content:`ボリュームラベルを作成・変更・削除。<br>$ *** C: MyLabel`},
{target:`subst`, content:`ドライブ名を割当て/解除。<br>$ *** Z: C:/Folder`},
{target:`runas`, content:`別ユーザの権限でプログラムを実行。<br>$ *** /user:Admin cmd`},
{target:`setlocal`, content:`環境変数のローカル化を開始。<br>$ ***`},
{target:`shift`, content:`コマンドライン引数をシフト。<br>$ ***`},
{target:`timeout`, content:`一定時間待機。<br>$ *** /T 10`},
{target:`convert`, content:`FATボリュームをNTFSに変換。<br>$ *** C: /FS:NTFS`},
{target:`eventcreate`, content:`イベントログを作成。<br>$ *** /T ERROR /ID 1000`},
{target:`schtasks`, content:`タスクの作成/変更/削除/表示。<br>$ *** /Query → タスクの表示<br> $ *** /Create /SC daily /TN Backup /TR backup.bat`},
{target:`sc`, content:`サービスに関する設定・確認。<br>$ *** query`},
{target:`doskey`, content:`コマンドのマクロを定義。<br>$ *** ls=dir`},
{target:`bootcfg`, content:`ブート構成を編集。<br>$ *** /Query`},
]
